- apt:
    name: nginx
    state: latest
  become: true


- service:
    name: nginx
    enabled: "{{not daemons_on_demand}}"
    state: started
  become: true


- apt:
    name:
      - apache2-utils
      - python3-passlib
    state: latest
  become: true
