- apt:
    name:
      - daemontools
      - runit
    state: latest
  become: true


- file:
    path: /etc/service
    state: directory
  become: true


- lineinfile:
    path: /etc/runit/2
    line: SVDIR=/etc/service
    regexp: '^#?\s*SVDIR\s*='
  become: true


- service:
    name: runit
    enabled: "{{not daemons_on_demand}}"
    state: started
  become: true
