- include_tasks: facts.yml

- file:
    path: "{{ data_dir }}"
    state: directory
    owner: etcd
    group: etcd
    mode: u=rwx,g=,o=
  become: true
  ignore_errors: true

- unarchive:
    dest: "{{ data_dir }}"
    src: "{{ cert_archive_file }}"
    include:
      - "{{ cert_archive_basedir }}/pki/ca.crt"
      - "{{ cert_archive_basedir }}/pki/issued/sc.{{ hostname }}.crt"
      - "{{ cert_archive_basedir }}/pki/private/sc.{{ hostname }}.key"
    owner: etcd
    group: etcd
  become: true
  ignore_errors: true

- name: member list
  shell: >
    etcdctl --endpoints={{ cluster_client_url }}
    --cacert="{{ data_dir }}/{{ cert_archive_basedir }}/pki/ca.crt"
    --cert="{{ data_dir }}/{{ cert_archive_basedir }}/pki/issued/sc.{{ hostname }}.crt"
    --key="{{ data_dir }}/{{ cert_archive_basedir }}/pki/private/sc.{{ hostname }}.key"
    member list | grep {{ etcd_id }} | awk -F, '{ print $1 }'
  environment:
    ETCDCTL_API: 3
  register: cluster_status
  become: true
  ignore_errors: true

- name: remove member
  command: >
    etcdctl --endpoints={{ cluster_client_url }}
    --cacert="{{ data_dir }}/{{ cert_archive_basedir }}/pki/ca.crt"
    --cert="{{ data_dir }}/{{ cert_archive_basedir }}/pki/issued/sc.{{ hostname }}.crt"
    --key="{{ data_dir }}/{{ cert_archive_basedir }}/pki/private/sc.{{ hostname }}.key"
    member remove {{ cluster_status.stdout }}
  environment:
    ETCDCTL_API: 3
  when: cluster_status.stdout
  become: true
  ignore_errors: true

- include_tasks: uninstall-{{ ansible_distribution | lower }}.yml

- file:
    path: "{{ data_dir }}"
    state: absent
  become: true
