- include_tasks: "pre-{{ansible_distribution|lower}}.yml"


- file:
    path: /opt/odoo
    state: directory
  become: true


- name: git shallow clone odoo to /opt/odoo
  git:
    repo: https://github.com/odoo/odoo
    dest: /opt/odoo/{{odoo_version}}
    version: "{{odoo_version}}.0"
    depth: 1
    force: yes
    recursive: yes
  become: true


- command: python{{python_version}} setup.py sdist
  args:
    chdir: /opt/odoo/{{odoo_version}}
  become: true


- file:
    path: "{{item}}"
    state: absent
  become: true
  with_items:
    - /opt/odoo/{{odoo_version}}/build
    - /opt/odoo/{{odoo_version}}/odoo.egg-info
