# imported by roles that wanted to use rsyslog master

- set_fact:
    rsyslog_host: 127.0.0.1
    rsyslog_port: "{{rsyslog_client_port | default(rsyslog_private_port)}}"
  when: use_stunnel


- set_fact:
    rsyslog_host: "{{groups['central-log'][0]}}"
    rsyslog_port: "{{rsyslog_private_port}}"
  when: not use_stunnel and rsyslog_exposed


- set_fact:
    rsyslog_host: 127.0.0.1
    rsyslog_port: "{{rsyslog_private_port}}"
  when: not use_stunnel and not rsyslog_exposed
