- apt:
    name:
      - haproxy
      - unzip
    state: latest
  become: true


- service:
    name: haproxy
    enabled: "{{not daemons_on_demand}}"
    state: started
  become: true
  ignore_errors: true
