- name: setup apt sources
  copy:
    dest: /etc/apt/sources.list
    content: |
      deb {{lookup('vars', 'debian_mirror', default='http://deb.debian.org/debian')}} stable main
      #deb {{lookup('vars', 'debian_mirror', default='http://deb.debian.org/debian')}} stable-security main
      deb {{lookup('vars', 'debian_mirror', default='http://deb.debian.org/debian')}} stable-updates main
      deb-src {{lookup('vars', 'debian_mirror', default='http://deb.debian.org/debian')}} stable main
      #deb-src {{lookup('vars', 'debian_mirror', default='http://deb.debian.org/debian')}} stable-security main
      deb-src {{lookup('vars', 'debian_mirror', default='http://deb.debian.org/debian')}} stable-updates main
  become: true

- command: dpkg --configure -a
  become: true

- apt:
    name:
      - libx11-*
      - libwayland-*
      - libreoffice-*
      - tango-icon-theme
    state: absent
    autoremove: true
    purge: true
  become: true
  ignore_errors: true
