- include_tasks: main-{{ansible_distribution|lower}}.yml

- file:
    path: "{{item}}"
    state: directory
  become: true
  with_items:
    - /etc/acme/certs
    - /etc/acme/config
    - /etc/acme/renew.d

- git:
    dest: /opt/acme.sh
    repo: https://github.com/acmesh-official/acme.sh
    depth: 1
    recursive: yes
    force: yes
  become: true

- copy:
    dest: /etc/cron.daily/renew-ssl-certificates
    content: |
        #!/bin/sh
        /bin/sh /opt/acme.sh/acme.sh --cron \
            --home /etc/acme --cert-home /etc/acme/certs \
            --config-home /etc/acme/config

    mode: u=rwx,g=rx,o=
  become: true


- command:
    cmd: >
        /bin/sh /opt/acme.sh/acme.sh
        --issue
        --email {{ssl_account_email}}
        --dns {{managed_domains[managed_domain].acme_provider}}
        --home /etc/acme
        --cert-home /etc/acme/certs
        --config-home /etc/acme/config
        --dnssleep 300
        --log --debug
        {% for domain in domains -%} -d '{{domain}}' {% endfor %}

    #--test
  become: true
  ignore_errors: true
  environment: "{{managed_domains[managed_domain].environment}}"
  when: verification == "dns"

- command:
    cmd: >
        /bin/sh /opt/acme.sh/acme.sh
        --issue
        --email {{ssl_account_email}}
        -w /var/www/html
        --home /etc/acme
        --cert-home /etc/acme/certs
        --config-home /etc/acme/config
        --log --debug
        {% for domain in domains -%} -d '{{domain}}' {% endfor %}

    #--test
  become: true
  ignore_errors: true
  when: verification == "webroot"


- command:
    cmd: >
        /bin/sh /opt/acme.sh/acme.sh
        --install-cert
        --home /etc/acme
        --cert-home /etc/acme/certs
        --config-home /etc/acme/config
        --fullchain-file '/etc/ssl/certs/{{cert_name}}.pem'
        --key-file '/etc/ssl/private/{{cert_name}}.key'
        --reloadcmd 'run-parts /etc/acme/renew.d'
        -d '{{cert_name}}'
  become: true
