- stat:
    path: "{{work_dir}}/pki/issued/c.{{ hostvars[item].hostname }}.crt"
  become: true
  register: test_stat

- file:
    path: "{{work_dir}}/pki/private/c.{{ hostvars[item].hostname }}.key"
    state: absent
  become: true
  when: not test_stat.stat.exists

- file:
    path: "{{work_dir}}/pki/reqs/c.{{ hostvars[item].hostname }}.req"
    state: absent
  become: true
  when: not test_stat.stat.exists

- expect:
    command: "{{work_dir}}/easyrsa --subject-alt-name='IP:{{item}},DNS:{{ hostvars[item].hostname }}' gen-req c.{{ hostvars[item].hostname }} nopass"
    chdir: "{{work_dir}}"
    responses:
      "Common Name \\(eg:": "{{ hostvars[item].hostname }}"
  become: true
  when: not test_stat.stat.exists

- expect:
    command: "{{work_dir}}/easyrsa sign-req client c.{{ hostvars[item].hostname }}"
    chdir: "{{work_dir}}"
    responses:
      "Confirm request details:": "yes"
  become: true
  when: not test_stat.stat.exists
