- stat:
    path: "{{work_dir}}/pki/issued/sc.{{ hostvars[item].hostname }}.crt"
  become: true
  register: test_stat

- file:
    path: "{{work_dir}}/pki/private/sc.{{ hostvars[item].hostname }}.key"
    state: absent
  become: true
  when: not test_stat.stat.exists

- file:
    path: "{{work_dir}}/pki/reqs/sc.{{ hostvars[item].hostname }}.req"
    state: absent
  become: true
  when: not test_stat.stat.exists

- expect:
    command: "{{work_dir}}/easyrsa --subject-alt-name='IP:{{ hostvars[item].ipv4|default(hostvars[item].ipv6, true) }},DNS:{{ hostvars[item].hostname }}' gen-req sc.{{ hostvars[item].hostname }} nopass"
    chdir: "{{work_dir}}"
    responses:
      "Common Name \\(eg:": "{{ hostvars[item].hostname }}"
  become: true
  when: not test_stat.stat.exists

- expect:
    command: "{{work_dir}}/easyrsa sign-req serverClient sc.{{ hostvars[item].hostname }}"
    chdir: "{{work_dir}}"
    responses:
      "Confirm request details:": "yes"
  become: true
  when: not test_stat.stat.exists
