- include_tasks: acme-{{ansible_distribution|lower}}.yml

- copy:
    src: "{{item.src}}"
    dest: /etc/dovecot/{{item.dest}}
    mode: "{{item.mode}}"
    remote_src: yes
    owner: "{{dovecot_unix_user}}"
    group: "{{dovecot_unix_group}}"
  notify: reload dovecot ({{ansible_distribution|lower}})
  become: true
  with_items:
    - src: /etc/ssl/certs/{{cert_name}}.pem
      dest: server.crt
      mode: u=rw,g=r,o=
    - src: /etc/ssl/private/{{cert_name}}.key
      dest: server.key
      mode: u=rw,g=,o=

- copy:
    src: "{{item.src}}"
    dest: /etc/postfix/{{item.dest}}
    mode: "{{item.mode}}"
    remote_src: yes
    owner: "{{postfix_unix_user}}"
    group: "{{postfix_unix_group}}"
  notify: reload postfix ({{ansible_distribution|lower}})
  become: true
  with_items:
    - src: /etc/ssl/certs/{{cert_name}}.pem
      dest: server.crt
      mode: u=rw,g=r,o=
    - src: /etc/ssl/private/{{cert_name}}.key
      dest: server.key
      mode: u=rw,g=,o=
