- apt:
    name:
      - dovecot-common
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-pgsql
      - dovecot-pop3d
      - python3-argon2 # needed by helper script
      - python3-psycopg2 # needed by helper script
    state: latest
  become: true

- name: install service
  service:
    name: dovecot
    enabled: "{{not daemons_on_demand}}"
    state: started
  become: true
  ignore_errors: true
