- import_tasks: facts.yml
- include_tasks: main-{{ansible_distribution|lower}}.yml

- import_tasks: opendkim.yml
- import_tasks: dovecot.yml

- unarchive:
    dest: /etc/postfix
    src: "{{ cert_archive_file }}"
    include:
      - "{{ cert_archive_basedir }}/pki/ca.crt"
      - "{{ cert_archive_basedir }}/pki/issued/{{ mta_database_user}}.{{ hostname }}.crt"
      - "{{ cert_archive_basedir }}/pki/private/{{ mta_database_user}}.{{ hostname }}.key"
    owner: postfix
    group: postfix
  become: true

- name: add postfix to opendkim group
  user:
    name: "{{postfix_unix_user}}"
    groups: "{{opendkim_unix_group}}"
    append: yes
  become: true


- name: configure main.cf
  lineinfile:
    dest: /etc/postfix/main.cf
    line: "{{item.line}}"
    regexp: "{{item.regex}}"
  become: true
  notify: restart postfix ({{ansible_distribution|lower}})
  with_items:
    - line: "myhostname = {{hostname}}"
      regex: '^#?myhostname\s*='

    # Outbound emails from this vps will get @myorigin, it defaults to
    # myhostname which could be a subdomain, so @mail.example.com, but you
    # wanted your sender to be @example.com
    - line: "myorigin = {{mta_domain}}"
      regex: '^#?myorigin\s*='

    - line: "mydestination = localhost"
      regex: '^#?mydestination\s*='

    - line: "smtpd_tls_cert_file = /etc/postfix/server.crt"
      regex: '^#?smtpd_tls_cert_file\s*='

    - line: "smtpd_tls_key_file = /etc/postfix/server.key"
      regex: '^#?smtpd_tls_key_file\s*='

    - line: "smtpd_use_tls = yes"
      regex: '^#?smtpd_use_tls\s*='

    - line: "smtpd_tls_auth_only = yes"
      regex: '^#?smtpd_tls_auth_only\s*='

    - line: "smtp_tls_security_level = may"
      regex: '^#?smtp_tls_security_level\s*='

    - line: "smtpd_tls_security_level = may"
      regex: '^#?smtpd_tls_security_level\s*='

    - line: "smtpd_sasl_type = dovecot"
      regex: '^#?smtpd_sasl_type\s*='

    - line: "smtpd_sasl_path = private/auth"
      regex: '^#?smtpd_sasl_path\s*='

    - line: "smtpd_sasl_auth_enable = yes"
      regex: '^#?smtpd_sasl_auth_enable\s*='

    - line: "smtpd_sasl_security_options = noanonymous, noplaintext"
      regex: '^#?smtpd_sasl_security_options\s*='

    - line: "smtpd_sasl_tls_security_options = noanonymous"
      regex: '^#?smtpd_sasl_tls_security_options\s*='

    - line: "mailbox_size_limit = 0"
      regex: '^#?mailbox_size_limit\s*='

    - line: "recipient_delimiter = +"
      regex: '^#?recipient_delimiter\s*='

    - line: "virtual_transport = lmtp:unix:private/dovecot-lmtp"
      regex: '^#?virtual_transport\s*='

    - line: "virtual_mailbox_domains = pgsql:/etc/postfix/pgsql-virtual-mailbox-domains.cf"
      regex: '^#?virtual_mailbox_domains\s*='

    - line: "virtual_mailbox_maps = pgsql:/etc/postfix/pgsql-virtual-mailbox-maps.cf"
      regex: '^#?virtual_mailbox_maps\s*='

    - line: "virtual_alias_maps = pgsql:/etc/postfix/pgsql-virtual-alias-maps.cf, pgsql:/etc/postfix/pgsql-virtual-email2email.cf"
      regex: '^#?virtual_alias_maps\s*='

    #- line: "smtpd_sender_login_maps = hash:/etc/postfix/controlled_envelope_senders"
    #  regex: '^#?smtpd_sender_login_maps\s*='

    #- line: "smtpd_sender_restrictions = reject_sender_login_mismatch, permit_sasl_authenticated"
    - line: "smtpd_sender_restrictions = permit_sasl_authenticated"
      regex: '^#?smtpd_sender_restrictions\s*='

    - line: "policyd-spf_time_limit = 8600"
      regex: '^#?policyd-spf_time_limit\s*='

    - line: "smtpd_recipient_restrictions = permit_sasl_authenticated, reject_unauth_destination, check_policy_service unix:private/policyd-spf"
      regex: '^#?smtpd_recipient_restrictions\s*='

    - line: "soft_bounce = yes"
      regex: '^#?soft_bounce\s*='

    - line: "smtpd_milters = unix:/run/opendkim/opendkim.sock"
      regex: '^#?smtpd_milters\s*='

    - line: "non_smtpd_milters = unix:/run/opendkim/opendkim.sock"
      regex: '^#?non_smtpd_milters\s*='


- name: configure master.cf
  template:
    dest: /etc/postfix/master.cf
    src: master.cf.j2
    owner: root
    group: postfix
    mode: o=
  become: true
  notify: reload postfix ({{ansible_distribution|lower}})


- name: setup database queries
  template:
    dest: /etc/postfix/pgsql-{{item}}.cf
    src: pgsql-{{item}}.cf.j2
    owner: root
    group: postfix
    mode: o=
  notify: restart postfix ({{ansible_distribution|lower}})
  become: true
  with_items:
    - virtual-mailbox-domains
    - virtual-mailbox-maps
    - virtual-alias-maps
    - virtual-email2email


#- name: allowed emails per login
#  copy:
#    dest: /etc/postfix/controlled_envelope_senders
#    content: |
#        {% for domain in mta_managed_domains %}
#        webmaster@onezone.shop  webmaster@onezone.shop, noreply@onezone.shop
#        {% endfor %}
#    owner: root
#    group: postfix
#    mode: o=
#  notify: restart postfix ({{ansible_distribution|lower}})
#  become: true


- name: /etc/postfix permissions
  file:
    path: /etc/postfix
    owner: root
    group: postfix
    mode: o=
    state: directory
  become: true


#- name: set mail admin user
#  lineinfile:
#    path: /etc/mail/aliases
#    line: "root:               postmaster@{{hostname}}"
#    regexp: '^#?\s*root:'
#    create: yes
#  become: true

- name: compile aliases db
  command: newaliases
  become: true


- name: firewall
  ufw:
    rule: allow
    port: "{{item}}"
    proto: tcp
    comment: postfix
  become: true
  when: use_ufw
  with_items:
    - 25
    - 465
    - 587
    - 110
    - 995
    - 143
    - 993
