- apt:
    name:
      - jetty9
      - runit
      - zookeeper
    state: latest
  become: true

- service:
    name: "{{item}}"
    enabled: "{{not daemons_on_demand}}"
    state: started
  become: true
  with_items:
    - runit
  ignore_errors: true
