- import_tasks: facts.yml
- include_tasks: main-{{ ansible_distribution | lower }}.yml

- file:
    path: "{{ item }}"
    state: absent
  become: true
  with_items:
    - "{{ rabbitmq_config_dir }}"
    - "{{ rabbitmq_data_dir }}"
