- include_tasks: main-{{ansible_distribution|lower}}.yml

- copy:
    dest: /etc/dovecot/{{item.dest}}
    src: /etc/ssl/{{item.src}}
    mode: "{{item.mode}}"
    remote_src: yes
    owner: "{{dovecot_unix_user}}"
    group: "{{dovecot_unix_group}}"
  become: true
  notify: reload dovecot ({{ansible_distribution|lower}})
  with_items:
    - dest: server.crt
      src: certs/{{cert_name}}.pem
      mode: u=rw,g=r,o=
    - dest: server.key
      src: private/{{cert_name}}.key
      mode: u=rw,g=,o=

- copy:
    dest: /etc/postfix/{{item.dest}}
    src: /etc/ssl/{{item.src}}
    mode: "{{item.mode}}"
    remote_src: yes
    owner: "{{postfix_unix_user}}"
    group: "{{postfix_unix_group}}"
  become: true
  notify: reload postfix ({{ansible_distribution|lower}})
  with_items:
    - dest: server.crt
      src: certs/{{cert_name}}.pem
      mode: u=rw,g=r,o=
    - dest: server.key
      src: private/{{cert_name}}.key
      mode: u=rw,g=,o=
