- name: reload postgresql (gentoo)
  service:
    name: postgresql-{{postgresql_version}}
    state: reloaded
  become: true


- name: restart postgresql (gentoo)
  service:
    name: postgresql-{{postgresql_version}}
    state: restarted
  become: true


- name: stop postgresql (gentoo)
  service:
    name: postgresql-{{postgresql_version}}
    state: stopped
  become: true
