- include_tasks: "{{ ansible_distribution|lower }}.yml"


- lineinfile:
    path: /etc/ssh/sshd_config
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  become: true
  notify: reload ssh ({{ ansible_distribution|lower }})
  with_items:
    - line: PermitRootLogin yes
      regexp: '^#?PermitRootLogin\s'
    - line: PasswordAuthentication no
      regexp: '^#?PasswordAuthentication\s'
    - line: ChallengeResponseAuthentication no
      regexp: '^#?ChallengeResponseAuthentication\s'
    - line: PubkeyAuthentication yes
      regexp: '^#?PubkeyAuthentication\s'
    - line: X11Forwarding no
      regexp: '^#?X11Forwarding\s'
    - line: AllowTcpForwarding no
      regexp: '^#?AllowTcpForwarding\s'
    - line: MaxAuthTries 3
      regexp: '^#?MaxAuthTries\s'

- lineinfile:
    path: /etc/ssh/sshd_config
    line: Port {{ ansible_port|default(22) }}
    regexp: '^#?Port\s'
  become: true
  notify: reload ssh ({{ ansible_distribution|lower }})
  when: ssh_ports is undefined

- blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "# {mark} ports"
    content: |
      {% for port in ssh_ports %}
      Port {{ port }}
      {% endfor %}
    insertafter: '^#?Port\s'
  become: true
  notify: reload ssh ({{ ansible_distribution|lower }})
  when: ssh_ports is defined


- import_tasks: sysadmin.yml
  when: create_sysadmin_user|default(false)


- blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "# {mark} root"
    content: |
      Match User root
          X11Forwarding no
          AllowTcpForwarding no
          PasswordAuthentication no
          PubkeyAuthentication yes
  become: true
  notify: reload ssh ({{ ansible_distribution|lower }})


- blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "# {mark} remote_admin"
    content: |
      Match User {{ ansible_user }}
          X11Forwarding no
          AllowTcpForwarding no
          PasswordAuthentication no
          PubkeyAuthentication yes
  become: true
  notify: reload ssh ({{ ansible_distribution|lower }})


- blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "# {mark} login_users"
    content: |
      {% for user in ssh_login_users %}
      Match User {{ user }}
          X11Forwarding yes
          AllowTcpForwarding yes
          PasswordAuthentication yes
          PubkeyAuthentication yes
      {% endfor %}
  become: true
  notify: reload ssh ({{ ansible_distribution|lower }})
  when: ssh_login_users is defined


# See: https://github.com/fail2ban/fail2ban/issues/3292#issuecomment-1142503461
- blockinfile:
    dest: /etc/fail2ban/jail.d/ssh.conf
    marker: "# {mark} ssh"
    content: |
      [sshd]
      enabled = true
      mode = aggressive
      backend = systemd
    create: true
  become: true
  notify: restart fail2ban ({{ ansible_distribution|lower }})
  when: use_ufw
