- name: create {{project}} unix group
  group:
    name: "{{lookup('vars', project + '_unix_group')}}"
    gid: "{{lookup('vars', project + '_unix_gid')}}"
  become: true


- name: create {{project}} unix user
  user:
    name: "{{lookup('vars', project + '_unix_user')}}"
    password: "{{lookup('vars', project + '_unix_password_crypted')}}"
    uid: "{{lookup('vars', project + '_unix_uid')}}"
    group: "{{lookup('vars', project + '_unix_group')}}"
    shell: "{{lookup('vars', project + '_login_shell', default='/bin/bash')}}"
    home: "{{lookup('vars', project + '_unix_home')}}"
    create_home: yes
  become: true
  ignore_errors: true


- file:
    name: "{{lookup('vars', project + '_unix_home')}}/.ssh"
    state: directory
    mode: u=rwx,g=,o=
  become: true
  become_user: "{{lookup('vars', project + '_unix_user')}}"


- file:
    path: "{{item}}"
    state: directory
  become: true
  become_user: "{{lookup('vars', project + '_unix_user')}}"
  with_items:
    - "{{lookup('vars', project + '_unix_home')}}/etc/service"
    - "{{lookup('vars', project + '_unix_home')}}/service"
    - "{{lookup('vars', project + '_unix_home')}}/var/log"
