- include_tasks: main-{{ansible_distribution|lower}}.yml

- copy:
    dest: /etc/nginx/{{item.dest}}
    src: /etc/ssl/{{item.src}}
    mode: "{{item.mode}}"
    remote_src: yes
    owner: "{{www_unix_user}}"
    group: "{{www_unix_group}}"
  become: true
  notify: reload nginx ({{ansible_distribution|lower}})
  with_items:
    - dest: "{{cert_name}}.pem"
      src: certs/{{cert_name}}.pem
      mode: u=rw,g=r,o=
    - dest: "{{cert_name}}.key"
      src: private/{{cert_name}}.key
      mode: u=rw,g=,o=
