- include_tasks: main-{{ansible_distribution | lower}}.yml


- ufw:
    rule: allow
    proto: tcp
    port: "{{ansible_port | default(22)}}"
    comment: ssh
  become: true
  when: ssh_ports is undefined

- ufw:
    rule: allow
    proto: tcp
    port: "{{item}}"
    comment: ssh
  become: true
  when: ssh_ports is defined
  with_items: "{{ssh_ports}}"


- name: Firewall default incoming policy
  ufw:
    direction: incoming
    policy: reject
  become: true


- name: Firewall default outgoing policy
  ufw:
    direction: outgoing
    policy: allow
  become: true


- ufw:
    state: enabled
  become: true


- service:
    name: "{{item}}"
    enabled: "{{not daemons_on_demand}}"
    state: started
  become: true
  ignore_errors: true
  with_items:
    - ufw
    - fail2ban


- include_tasks: monit-{{ansible_distribution|lower}}.yml
  when: use_monit
