- file:
    path: /etc/monit/monitrc.d/fail2ban
    state: absent
  become: true


- copy:
    dest: /etc/monit/conf-available/fail2ban
    content: |
        check process fail2ban with pidfile /var/run/fail2ban/fail2ban.pid
            group services
            start program = "/etc/init.d/fail2ban force-start"
            stop  program = "/etc/init.d/fail2ban stop"
            if failed unixsocket /var/run/fail2ban/fail2ban.sock then restart
            if 5 restarts within 5 cycles then timeout                                                                                

        check file fail2ban_log with path /var/log/fail2ban.log
            if match "ERROR|WARNING" then alert

  notify: reload monit ({{ansible_distribution|lower}})
  become: true


- file:
    dest: /etc/monit/conf-enabled/fail2ban
    src: /etc/monit/conf-available/fail2ban
    state: link
  become: true
