- name: restart rabbitmq (debian)
  service:
    name: rabbitmq-server
    state: restarted
  become: true


- name: reload rabbitmq (debian)
  service:
    name: rabbitmq-server
    state: reloaded
  become: true
