- apt:
    name:
      - etcd-client
      - etcd-server
      - unzip
    state: latest
  become: true

- service:
    name: "{{item}}"
    enabled: false
    state: stopped
  become: true
  with_items:
    - etcd
