- timezone:
    name: "{{timezone}}"
  become: true

- name: setup apt sources
  copy:
    dest: /etc/apt/sources.list
    content: |
      deb {{lookup('vars', 'debian_mirror', default='http://deb.debian.org/debian')}} stable main
      #deb {{lookup('vars', 'debian_mirror', default='http://deb.debian.org/debian')}} stable-security main
      deb {{lookup('vars', 'debian_mirror', default='http://deb.debian.org/debian')}} stable-updates main
      deb-src {{lookup('vars', 'debian_mirror', default='http://deb.debian.org/debian')}} stable main
      #deb-src {{lookup('vars', 'debian_mirror', default='http://deb.debian.org/debian')}} stable-security main
      deb-src {{lookup('vars', 'debian_mirror', default='http://deb.debian.org/debian')}} stable-updates main
  become: true

- command: dpkg --configure -a
  become: true


- name: update cache of apt
  apt:
    autoremove: yes
    autoclean: yes
    update_cache: yes
    upgrade: yes
  ignore_errors: yes
  become: true


- apt:
    name:
      - aptitude
      - acl
      - net-tools
      - xtail
      - rsync
      - tmux
      - htop
    state: latest
  become: true


- blockinfile:
    marker: '# {mark} server'
    path: /etc/rc.local
    content: |
      {% if sys_kernel_mm_transparent_hugepage_enabled is defined %}
      if [ -e /sys/kernel/mm/transparent/hugepage/enabled ]
      then
          echo {{sys_kernel_mm_transparent_hugepage_enabled}} > /sys/kernel/mm/transparent_hugepage/enabled
      fi
      {% endif %}
    insertbefore: '^exit 0'
    create: yes
    mode: u=rwx,g=rx,o=
  become: true
