- name: create syadmin user
  user:
    name: "{{sysadmin_unix_user}}"
    password: "{{sysadmin_unix_password_crypted}}"
    shell: /bin/bash
  become: true


- name: add sysadmin to sudo group
  user:
    name: "{{sysadmin_unix_user}}"
    append: yes
    groups:
      - "{{sudo_unix_group}}"
  become: true


