- copy:
    dest: /etc/acme/renew.d/postgresql
    content: |
        #!/bin/sh
        cp /etc/ssl/certs/{{cert_name}}.pem {{postgresql_config_dir}}/server.crt
        cp /etc/ssl/private/{{cert_name}}.key {{postgresql_config_dir}}/server.key
        chown postgres:postgres {{postgresql_config_dir}}/server.*
        chmod u=rw,g=r,o= {{postgresql_config_dir}}/server.crt
        chmod u=rw,g=,o= {{postgresql_config_dir}}/server.key
        systemctl reload postgresql

    mode: u=rwx,g=rx,o=rx
  become: true
