- include_tasks: acme-{{ansible_distribution|lower}}.yml

- copy:
    src: "{{item.src}}"
    dest: "{{postgresql_config_dir}}/{{item.dest}}"
    mode: "{{item.mode}}"
    remote_src: yes
    owner: postgres
    group: postgres
  become: true
  notify: reload postgresql ({{ansible_distribution|lower}})
  with_items:
    - src: /etc/ssl/certs/{{cert_name}}.pem
      dest: server.crt
      mode: u=rw,g=r,o=
    - src: /etc/ssl/private/{{cert_name}}.key
      dest: server.key
      mode: u=rw,g=,o=
