- copy:
    dest: /etc/letsencrypt/renewal-hooks/deploy/postgresql.sh
    content: |
      #!/bin/sh
      umask 0177
      cp /etc/letsencrypt/live/{{postgresql_ssl_certname}}/fullchain.pem {{postgresql_data_dir}}/server.crt
      cp /etc/letsencrypt/live/{{postgresql_ssl_certname}}/privkey.pem {{postgresql_data_dir}}/server.key
      chown postgres:postgres {{postgresql_data_dir}}/server.crt {{postgresql_data_dir}}/server.key
      /etc/init.d/postgresql-{{postgresql_version}} reload
    mode: u=rwx,g=r,o=
  become: true


- copy:
    dest: "{{postgresql_data_dir}}/server.key"
    src: /etc/letsencrypt/live/{{postgresql_ssl_certname}}/privkey.pem
    remote_src: yes
    owner: postgres
    group: postgres
    mode: u=r,g=,o=
    follow: true
  become: true
  notify: reload postgresql ({{ansible_distribution | lower}})


- copy:
    dest: "{{postgresql_data_dir}}/server.crt"
    src: /etc/letsencrypt/live/{{postgresql_ssl_certname}}/fullchain.pem
    remote_src: yes
    owner: postgres
    group: postgres
    mode: u=r,g=r,o=
    follow: true
  become: true
  notify: reload postgresql ({{ansible_distribution | lower}})
