- command: sed -nr 's/^PORTDIR="(.*)"/\1/p;' /etc/portage/make.conf
  register: portdir_cmd

- command: mount "{{portdir_cmd.stdout}}"
  become: true
  ignore_errors: yes


- command: sed -nr 's/^DISTDIR="(.*)"/\1/p;' /etc/portage/make.conf
  register: distdir_cmd

- command: mount "{{distdir_cmd.stdout}}"
  become: true
  ignore_errors: yes


- name: install ansible package requirements
  portage:
    name:
      - sys-apps/dmidecode
  become: True


- name: update ansible package requirements
  portage:
    name:
      - sys-apps/dmidecode
    state: latest
    deep: yes
    newuse: yes
  become: True
