- include_tasks: "{{ansible_distribution|lower}}.yml"


- file:
    path: /root/bin
    state: directory
  become: true


- include_vars:
    dir: "{{inventory_dir}}/group_vars/{{inv_group_dns}}"
    name: dns

- template:
    src: certbot-{{dns_provider}}-dns-auth.j2
    dest: /root/bin/certbot-dns-auth
    mode: u=rwx,g=rx,o=
  become: true

- template:
    src: certbot-{{dns_provider}}-dns-cleanup.j2
    dest: /root/bin/certbot-dns-cleanup
    mode: u=rwx,g=rx,o=
  become: true


- command: >
      certbot certonly --agree-tos --email {{letsencrypt_email}}
      --cert-name {{ssl_certname}}
      --preferred-challenges dns-01
      --manual
      --manual-auth-hook /root/bin/certbot-dns-auth
      --manual-cleanup-hook /root/bin/certbot-dns-cleanup
      --manual-public-ip-logging-ok
      {% for domain in letsencrypt_domains -%}
      -d {{domain}}
      {% endfor %}
  args:
    creates: /etc/letsencrypt/renewal/{{ssl_certname}}.conf
  become: true
