- include_tasks: main-{{ ansible_distribution | lower }}.yml
- include_tasks: facts.yml

- file:
    path: "{{ data_dir }}"
    state: directory
    owner: etcd
    group: etcd
    mode: u=rwx,g=,o=
  become: true

- unarchive:
    dest: "{{ data_dir }}"
    src: "{{ cert_archive_file }}"
    include:
      - "{{ cert_archive_basedir }}/pki/ca.crt"
      - "{{ cert_archive_basedir }}/pki/issued/sc.{{ hostname }}.crt"
      - "{{ cert_archive_basedir }}/pki/private/sc.{{ hostname }}.key"
    owner: etcd
    group: etcd
  become: true

- name: Setup etcd
  template:
    dest: /etc/default/etcd
    src: etcd.j2
  become: true
  notify: restart etcd ({{ ansible_distribution | lower }})

- ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    comment: etcd
  become: true
  with_items:
    - "2379"
    - "2380"
